export const EVENT_TYPE_VALUES = [
  "organization:member_added",
  "organization:member_removed",
  "organization:invitation_created",
  "organization:invitation_accepted",
  "organization:invitation_revoked",
  "organization:invitation_declined",
  "api-key:created",
  "api-key:revoked",
  "api-key:updated",
  "api-key:rolled",
  "registry-repository:created",
  "registry-access-token:created",
  "registry-access-token:updated",
  "registry-access-token:revoked",
  "verification:created",
  "verification:completed",
  "container:created",
  "container:updated",
  "container:removed",
  "database:created",
  "database:updated",
  "database:deleted",
  "database:linked",
  "database:unlinked",
] as const;

export type EventType = typeof EVENT_TYPE_VALUES[number];
