import type { components } from './generated.ts'

export type Project = components['schemas']['ProjectResponse']
export type Environment = components['schemas']['EnvironmentResponse']
export type EnvironmentWithProject = components['schemas']['EnvironmentWithProjectResponse']
export type TimelineRevision = components['schemas']['TimelineResponse']
export type ResolvedTimeline = components['schemas']['ResolvedTimelineResponse']
export type ResolvedContainer = components['schemas']['ResolvedContainerPin']
export type Container = components['schemas']['ContainerResponse']
export type ContainerVersion = components['schemas']['ContainerVersionResponse']
export type Database = components['schemas']['DatabaseResponse']
export type DatabaseBranch = components['schemas']['DatabaseBranchResponse']
export type Bucket = components['schemas']['BucketResponse']
export type Region = components['schemas']['RegionResponse']
export type Repository = components['schemas']['RegistryRepositoryResponse']
export type StorageAccessToken = components['schemas']['AccessTokenResponse']
export type StorageAccessTokenDetails = components['schemas']['AccessTokenDetailsResponse']
export type CreatedStorageAccessToken = components['schemas']['CreatedAccessTokenResponse']
export type RegistryAccessToken = components['schemas']['RegistryAccessTokenResponse']
export type RegistryAccessTokenDetails = components['schemas']['RegistryAccessTokenDetailsResponse']
export type CreatedRegistryAccessToken = components['schemas']['CreatedRegistryAccessTokenResponse']
export type RegistryToken = components['schemas']['RegistryTokenResponse']
export type BucketPermission = components['schemas']['BucketPermissionRequest']
export type RepositoryPermission = components['schemas']['RepositoryPermissionRequest']
export type Event = components['schemas']['EventResponse']
