ARG PACKAGE=ui

FROM oven/bun:1.2.9 AS base
ARG PACKAGE
WORKDIR /usr/src/app

COPY package.json ./package.json
COPY bun.lock ./bun.lock
COPY packages/ui-shared/package.json ./packages/ui-shared/package.json
COPY packages/ui/package.json ./packages/ui/package.json
COPY packages/control-plane-ui/package.json ./packages/control-plane-ui/package.json

RUN bun install --frozen-lockfile --filter "./packages/${PACKAGE}"

COPY packages/ui-shared/schema ./packages/ui-shared/schema
COPY packages/ui-shared/types ./packages/ui-shared/types
COPY packages/ui-shared/utils ./packages/ui-shared/utils
COPY packages/${PACKAGE} ./packages/${PACKAGE}

WORKDIR /usr/src/app/packages/${PACKAGE}

FROM base AS development
WORKDIR /usr/src/app/packages/${PACKAGE}
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=250
ENV WATCHPACK_POLLING=true
CMD ["bun", "--bun", "run", "dev"]

FROM base AS production-prepack
WORKDIR /usr/src/app/packages/${PACKAGE}
RUN bun run --bun build

FROM oven/bun:1.2.9 AS production
ARG PACKAGE
WORKDIR /usr/src/app/packages/${PACKAGE}
COPY --from=production-prepack /usr/src/app/packages/${PACKAGE}/.output ./.output
CMD ["bun", "run", "./.output/server/index.mjs"]
