export const ERRORS = {
  ENCRYPTION: {
    USER_ALREADY_HAS_RK_KEYS: "USER_ALREADY_HAS_RK_KEYS",
    USER_HAS_NO_RK_KEYS: "USER_HAS_NO_RK_KEYS",
    ORGANIZATION_HAS_NO_RK_KEYS: "ORGANIZATION_HAS_NO_RK_KEYS",
  },
  USER: {
    NOT_FOUND: "USER_NOT_FOUND",
  },
  ORGANIZATION: {
    NOT_FOUND: "ORGANIZATION_NOT_FOUND",
    INVALID_ID: "ORGANIZATION_INVALID_ID",
    SLUG_IN_USE: "ORGANIZATION_SLUG_IN_USE",
  },
  INVALID_REQUEST: "INVALID_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  PROCESSING: "PROCESSING",
  SERVER_ERROR: "SERVER_ERROR",
}
