[package]
name = "c-plane"
version = "0.1.0"
edition = "2024"

[features]
default = []
cloud = []

[dependencies]
sea-orm = { version = "1.1.15", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "debug-print"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15.7"
actix-web = "4.11.0"
futures-util = "0.3"
tracing-subscriber = "0.3.20"
