use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "c-plane API",
        version = "0.1.0",
        description = "Control plane API for managing projects, environments, containers, and databases",
    ),
    paths(
        crate::handlers::projects::create_project,
        crate::handlers::projects::list_projects,
        crate::handlers::projects::get_project,
        crate::handlers::projects::delete_project,
        crate::handlers::projects::list_organization_environments,
        crate::handlers::projects::list_environments,
        crate::handlers::projects::create_environment,
        crate::handlers::projects::update_environment,
        crate::handlers::projects::delete_environment,
        crate::handlers::projects::list_project_timelines,
        crate::handlers::projects::get_timeline,
        crate::handlers::events::list_events,
        crate::handlers::health::health_check,
        crate::handlers::regions::list_regions,
        crate::handlers::containers::create_container,
        crate::handlers::containers::list_containers,
        crate::handlers::containers::get_container,
        crate::handlers::containers::update_container,
        crate::handlers::containers::delete_container,
        crate::handlers::postgres_databases::create_database,
        crate::handlers::postgres_databases::list_databases,
        crate::handlers::postgres_databases::get_database,
        crate::handlers::postgres_databases::update_database,
        crate::handlers::postgres_databases::delete_database,
        crate::handlers::postgres_databases::list_database_branches,
        crate::handlers::postgres_databases::update_database_branch,
        crate::handlers::postgres_databases::create_database_branch,
        crate::handlers::postgres_databases::delete_database_branch,
        crate::handlers::storage_buckets::create_bucket,
        crate::handlers::storage_buckets::delete_bucket,
        crate::handlers::storage_buckets::list_buckets,
        crate::handlers::storage_access_tokens::create_access_token,
        crate::handlers::storage_access_tokens::get_access_token,
        crate::handlers::storage_access_tokens::list_access_tokens,
        crate::handlers::storage_access_tokens::revoke_access_token,
        crate::handlers::storage_access_tokens::update_access_token,
        crate::handlers::registry::issue_token,
        crate::handlers::registry::maintenance_status,
        crate::handlers::registry_access_tokens::create_access_token,
        crate::handlers::registry_access_tokens::get_access_token,
        crate::handlers::registry_access_tokens::list_access_tokens,
        crate::handlers::registry_access_tokens::revoke_access_token,
        crate::handlers::registry_access_tokens::update_access_token,
        crate::handlers::registry_repositories::create_repository,
        crate::handlers::registry_repositories::list_repositories,
        crate::handlers::registry_repositories::delete_repository,
    ),
    components(
        schemas(
            crate::errors::ErrorResponse,
            crate::handlers::projects::CreateProjectRequest,
            crate::handlers::projects::ProjectResponse,
            crate::handlers::projects::CreateEnvironmentRequest,
            crate::handlers::projects::UpdateEnvironmentRequest,
            crate::handlers::projects::EnvironmentResponse,
            crate::handlers::projects::EnvironmentWithProjectResponse,
            crate::handlers::projects::TimelineResponse,
            crate::handlers::projects::ResolvedContainerPin,
            crate::handlers::projects::ResolvedTimelineResponse,
            crate::handlers::health::HealthResponse,
            crate::handlers::regions::RegionResponse,
            crate::handlers::events::EventResponse,
            crate::handlers::containers::CreateContainerRequest,
            crate::handlers::containers::UpdateContainerRequest,
            crate::handlers::containers::ContainerResponse,
            crate::handlers::containers::ContainerVersionResponse,
            crate::handlers::databases::CreateDatabaseRequest,
            crate::handlers::databases::UpdateDatabaseRequest,
            crate::handlers::databases::DatabaseResponse,
            crate::handlers::databases::CreateDatabaseBranchRequest,
            crate::handlers::databases::UpdateDatabaseBranchRequest,
            crate::handlers::databases::DatabaseBranchResponse,
            crate::utils::pagination::PaginatedResponse<crate::handlers::projects::ProjectResponse>,
            crate::utils::pagination::PaginationMeta,
            crate::handlers::storage_buckets::CreateBucketRequest,
            crate::handlers::storage_buckets::BucketResponse,
            crate::handlers::storage_access_tokens::CreateAccessTokenRequest,
            crate::handlers::storage_access_tokens::UpdateAccessTokenRequest,
            crate::handlers::storage_access_tokens::BucketPermissionRequest,
            crate::handlers::storage_access_tokens::AccessTokenResponse,
            crate::handlers::storage_access_tokens::AccessTokenDetailsResponse,
            crate::handlers::storage_access_tokens::CreatedAccessTokenResponse,
            crate::handlers::registry::RegistryTokenResponse,
            crate::handlers::registry::RegistryMaintenanceResponse,
            crate::handlers::registry_access_tokens::CreateRegistryAccessTokenRequest,
            crate::handlers::registry_access_tokens::UpdateRegistryAccessTokenRequest,
            crate::handlers::registry_access_tokens::RepositoryPermissionRequest,
            crate::handlers::registry_access_tokens::RegistryAccessTokenResponse,
            crate::handlers::registry_access_tokens::RegistryAccessTokenDetailsResponse,
            crate::handlers::registry_access_tokens::CreatedRegistryAccessTokenResponse,
            crate::handlers::registry_repositories::CreateRegistryRepositoryRequest,
            crate::handlers::registry_repositories::RegistryRepositoryResponse,
        ),
    ),
    tags(
        (name = "projects", description = "Project management"),
        (name = "environments", description = "Environment management"),
        (name = "containers", description = "Container management"),
        (name = "events", description = "Organization activity"),
        (name = "databases/postgres", description = "Postgres database management"),
        (name = "storage", description = "S3 bucket and access token management"),
        (name = "registry", description = "OCI registry authentication"),
    ),
)]
pub struct ApiDoc;
