#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ui WITH PASSWORD '$POSTGRES_UI_PASSWORD';
    
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ui;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ui;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ui;
    GRANT ALL PRIVILEGES ON SCHEMA public TO ui;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ui;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ui;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO ui;
EOSQL
