#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ui WITH PASSWORD '${POSTGRES_UI_PASSWORD}';
    CREATE ROLE app_identity NOLOGIN;
    CREATE ROLE app_tenant NOLOGIN;
    CREATE ROLE app_admin NOLOGIN;
    CREATE USER cplane_identity WITH PASSWORD '${POSTGRES_IDENTITY_PASSWORD}';
    CREATE USER cplane_tenant WITH PASSWORD '${POSTGRES_TENANT_PASSWORD}';
    CREATE USER cplane_admin WITH PASSWORD '${POSTGRES_ADMIN_PASSWORD}';


    GRANT app_identity TO cplane_identity;
    GRANT app_tenant TO cplane_tenant;
    GRANT app_admin TO cplane_admin;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ui, cplane_identity, cplane_tenant, cplane_admin;

    GRANT ALL PRIVILEGES ON SCHEMA public TO ui;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ui;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ui;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ui;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ui;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ui;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO ui;

    GRANT USAGE ON SCHEMA public TO app_identity, app_tenant, app_admin;

    GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_identity;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO app_identity;

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_tenant;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_tenant;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_tenant;

    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_admin;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_admin;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO app_admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO app_admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO app_admin;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO app_admin;

    ALTER ROLE app_admin BYPASSRLS;
    ALTER ROLE app_identity BYPASSRLS;
    ALTER ROLE cplane_admin BYPASSRLS;
    ALTER ROLE cplane_identity BYPASSRLS;
EOSQL
