version: 0.1

log:
  level: info
  formatter: json

http:
  addr: :5000
  debug:
    addr: :5001
    prometheus:
      enabled: true
      path: /metrics

storage:
  cplane:
    controlplaneurl: http://api:8080
    servicetoken: development-only
    cachecapacity: 256
    cachettl: 15m
  redirect:
    disable: true
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: false

auth:
  cplane:
    realm: http://localhost:8080/api/registry/token
    service: localhost:5000
    issuer: cplane-registry

validation:
  disabled: false
